dist: trusty
language: python
addons:
    apt:
        packages:
            - bwa
            - cloc
branches:
  only:  # don't build "pushes" except on the master branch
    - master
cache: pip
python:
    - 2.7
    - 3.5
install:
    - make devenv
    - pip install wheel
    - pip install pysam>=0.11.2
    - pip install -r requirements.txt
    - pip install .
script:
    - find /home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages -type f -name "*alignment*.so"
    - make testall
    - make style
    - make doc
after_success:
    - make loc
    - bash <(curl -s https://codecov.io/bash)
