dist: trusty
language: python
branches:
  only:  # don't build "pushes" except on the master branch
    - master
cache:
    directories:
        - $HOME/virtualenv/python2.7
        - $HOME/virtualenv/python3.5
python:
    - 2.7
    - 3.5
install:
    - pip install --upgrade pip setuptools pytest-cov pep8 cython
    - pip install pysam
    - pip install git+https://github.com/dib-lab/khmer.git@feature/consume_bitsplit
    - pip install .
script:
    - make testall
    - make style
