dist: trusty
language: python
addons:
    apt:
        packages:
            - bwa
            - cloc
branches:
  only:  # don't build "pushes" except on the master branch
    - master
cache: pip
python:
    - 3.5
    - 3.6
install:
    - make devenv
    - pip install wheel
    - pip install -r requirements.txt
    - pip install .
script:
    - make testmore
    - make style
    - make doc
after_success:
    - make loc
    - bash <(curl -s https://codecov.io/bash)
